config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users
  get 'pages/home'
  get 'pages/export'
  get 'pages/export/companies', to: 'pages#csv'
  resources :companies do
    resources :comments
  end

  namespace :admin do
    resources :users
    resources :companies

    root to: 'users#index'
  end
end

app/views/shared/_login_modal.html.haml
:ruby
  new_user = User.new

%input#login-modal.modal-toggle{:type => "checkbox"}/
%label.modal.cursor-pointer{:for => "login-modal"}
  %label.modal-box.relative.relative.flex.flex-col.gap-3.items-center{:for => ""}
    %h2.text-2xl Log in
    = form_for(:user, url: session_path(:user), html: { class: 'flex flex-col space-y-2' }) do |f|
      .field
        = f.label :email
        %br/
        = f.email_field :email, autofocus: true, autocomplete: "email", class: 'input input-bordered w-full max-w-xs'
      .field
        = f.label :password
        %br/
        = f.password_field :password, autocomplete: "current-password", class: 'input input-bordered w-full max-w-xs'
      - if Devise.mappings[:user].rememberable?
        .field
          = f.check_box :remember_me, class: 'checkbox'
          = f.label :remember_me, class: 'label-text'
      .actions
        = f.submit "Log in", class: 'btn btn-primary'
      %ul
        %li
          = link_to("Sign up", new_registration_path(:user))
        %li
          = link_to("Forgot your password?", new_password_path(:user))

app/views/shared/_sign_up_modal.html.haml
:ruby
  new_user = User.new

%input#sign-up-modal.modal-toggle{:type => "checkbox"}/
%label.modal.cursor-pointer{:for => "sign-up-modal"}
  %label.modal-box.relative.flex.flex-col.gap-3.items-center{:for => ""}
    %h2.text-2xl Sign up
    = form_for(new_user, as: :user, url: registration_path(:user), html: { class: 'flex flex-col space-y-4' }) do |f|
      = render "users/shared/error_messages", resource: new_user
      .field
        = f.label :email
        %br/
        = f.email_field :email, autofocus: true, autocomplete: "email", class: 'input input-bordered w-full max-w-xs'
      .field
        = f.label :password
        - if @minimum_password_length
          %em
            (#{@minimum_password_length} characters minimum)
        %br/
        = f.password_field :password, autocomplete: "new-password", class: 'input input-bordered w-full max-w-xs'
      .field
        = f.label :password_confirmation
        %br/
        = f.password_field :password_confirmation, autocomplete: "new-password", class: 'input input-bordered w-full max-w-xs'
      .actions
        = f.submit "Sign up", class: 'btn btn-error'
      %ul
        %li
          = link_to("Log in", new_session_path(:user))
        %li
          = link_to("Forgot your password?", new_password_path(:user))