config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users
  get 'pages/home'
  get 'pages/export'
  get 'pages/export/companies', to: 'pages#csv'
  resources :companies do
    resources :comments
  end

  namespace :admin do
    resources :users
    resources :companies

    root to: 'users#index'
  end
end

app/views/pages/companies.csv.haml
= CSV.generate_line(['Name', 'Url', 'Location'], row_sep: nil)
- @companies.each do |company|
  = CSV.generate_line([company.name, company.url, company.location], row_sep: nil)

app/views/pages/export.html.haml
.flex.justify-center
  %div
    %h2.text-6xl
      Export Ruby Companies
    %p
      This list of #{@number_of_companies} companies was a collaborative effort to help out rails developers. Specially, juniors. I believe we should do all that is in our hands to help each other out, specially given how niche Ruby On Rails is in Spain.
    %p
      I would hate for this info to go to waste, not to mention the info is scarce and a pain in the ass to collect. Please feel encourage to keep it as it is yours, share it and help your fellow rubyist.
    = link_to('See you in another life brotha!', 'https://www.youtube.com/watch?v=zPt5OmNmgi0', class: 'link')
    = link_to('Download CSV', pages_export_companies_path(format: :csv), class: 'btn btn-primary')

app/views/pages/home.html.haml
.flex.flex-col
  .flex.justify-center.items-center
    = image_tag('ruby.png', class: 'w-1/3', alt: 'a Ruby, Ruby, Ruby')
    %div
      %h1.font-bold.text-4xl.mb-6
        Spain on
        %span.text-red-700 Rails
      %p Resistiré, para seguir viviendo
      %p Soportaré los golpes y jamás me rendiré
      %p Y aunque los sueños se me rompan en pedazos
      %p Resistiré, resistiré
      %p.mt-2 -a Spanish Ruby On Rails Developer, probably
  .flex.justify-center
    = link_to('See Ruby companies', companies_path, class: 'btn btn-error')