config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users
  get 'pages/home'
  get 'pages/export'
  get 'pages/export/companies', to: 'pages#csv'
  resources :companies do
    resources :comments
  end

  namespace :admin do
    resources :users
    resources :companies

    root to: 'users#index'
  end
end

app/models/company.rb
# frozen_string_literal: true

class Company < ApplicationRecord
  LOCATIONS = Companies::ListCompaniesLocationsUseCase.call

  has_many :comments, dependent: :destroy

  scope :by_province, ->(province) { where('location ILIKE :province', province: province) }

  validates :name, presence: true, uniqueness: true
  validates :location, inclusion: { in: LOCATIONS, message: '%<value> is not a valid Spanish location' }
  validate :valid_url?

  def has_comments?
    comments_count.positive?
  end

  private

  def valid_url?
    return true if UrlValidator.new(url: url).valid?

    self.errors.add(:url, "#{url} is not a valid url!")
  end
end

app/controllers/admin/companies_controller.rb
module Admin
  class CompaniesController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: %i[show edit update destroy]
  before_action :set_locations, only: %i[index edit create]
  before_action :authenticate_user!, only: %i[edit]

  # GET /companies or /companies.json
  def index
    # TODO: Time to turn it into a UseCase is coming
    scope = policy_scope(Company)
    scope = scope.by_province(params[:province]) if params[:province].present?
    @companies = scope.page(params[:page]).per(9)
  end

  # GET /companies/1 or /companies/1.json
  def show
    parent_comments = @company.comments.parents
    @comments = parent_comments.with_author.with_replies

    @comment = @company.comments.build

    authorize @company
  end

  # GET /companies/new
  def new
    @company = Company.new
    authorize @company
  end

  # GET /companies/1/edit
  def edit
    authorize @company
  end

  # POST /companies or /companies.json
  def create
    @company = Company.new(company_params)
    authorize @companies

    respond_to do |format|
      if @company.save
        format.html { redirect_to company_url(@company), notice: "Company was successfully created." }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1 or /companies/1.json
  def update
    authorize @company

    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to company_url(@company), notice: "Company was successfully updated." }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1 or /companies/1.json
  def destroy
    authorize(@company)

    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url, notice: "Company was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_company
    @company = Company.find(params[:id])
  end

  def set_locations
    @locations = Company::LOCATIONS
  end

  def company_params
    params.require(:company).permit(:name, :url, :location)
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_company.html.haml
%div{:id => "#{dom_id company}"}
  %p.my-5
    %strong.block.font-medium.mb-1 Name:
    = company.name
  %p.my-5
    %strong.block.font-medium.mb-1 Url:
    = company.url
  %p.my-5
    %strong.block.font-medium.mb-1 Location:
    = company.location
  - if action_name != "show"
    = link_to "Show this company", company, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"

app/views/companies/_form.html.haml
= form_with(model: company, class: "contents") do |form|
  - if company.errors.any?
    #error_explanation.bg-red-50.text-red-500.px-3.py-2.font-medium.rounded-lg.mt-3
      %h2
        = pluralize(company.errors.count, "error")
        prohibited this company from being saved:
      %ul
        - company.errors.each do |error|
          %li= error.full_message
  .my-5
    = form.label :name
    = form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .my-5
    = form.label :url
    = form.text_field :url, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .my-5
    = form.select :location, options_for_select(@locations, company.location), { include_blank: "Selecciona una provincia" }, { class: 'select select-bordered w-full max-w-xs select select-bordered w-full max-w-xs'}
  .inline
    = form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer"

app/views/companies/edit.html.haml
.mx-auto.w-full{:class => "md:w-2/3"}
  %h1.font-bold.text-4xl Editing company
  = render "form", company: @company
  = link_to "Show this company", @company, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
  = link_to "Back to companies", companies_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"

app/views/companies/index.html.haml
%div
  - if notice.present?
    %p#notice.py-2.px-3.bg-green-50.mb-5.text-green-500.font-medium.rounded-lg.inline-block= notice
  .flex.justify-between.items-center
    %h1.font-bold.text-4xl 
      Companies
    .flex.gap-4
      = render(DropdownFilterComponent.new(options: @locations, selected_option: params[:province], placeholder: 'Filter by Province'))
      = link_to('Export List', pages_export_path, class: 'btn')
  .grid.grid-cols-3.gap-4
    = render @companies
  = paginate @companies

app/views/companies/new.html.haml
.mx-auto.w-full{:class => "md:w-2/3"}
  %h1.font-bold.text-4xl New company
  = render "form", company: @company
  = link_to 'Back to companies', companies_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"

app/views/companies/show.html.haml
.mx-auto.flex.flex-row{:class => "md:w-2/3"}
  .mx-auto
    - if notice.present?
      %p#notice.py-2.px-3.bg-green-50.mb-5.text-green-500.font-medium.rounded-lg.inline-block= notice
    = render @company
    - if current_user&.admin?
      = render(ButtonComponent.new(type: :accent, url: edit_company_path(@company))) do
        = 'Edit this company'
      .inline-block.ml-2
        = render(ButtonComponent.new(type: :error, url: company_path(@company), method: :delete)) do
          = 'Destroy this company'
    = render(ButtonComponent.new(type: :ghost, url: companies_path)) do
      = 'Back to companies'
    - if @company.has_comments?
      %h3.mt-8.text-2xl
        #{@company.comments_count} Comments
      = render(CommentComponent.with_collection(@comments, current_user: current_user))
    - else
      %h3
        Comments
      %h4="No comments yet :( Be the first one!"
    = render partial: "comments/form", locals: { comment: @comment, company: @company }